### ISSUE TITLE
Desired font will not work on GitHub hosting

### ISSUE THREAD

**Issue by kgh0054** [codyqhogan/codyqhogan.github.io#4]
Same code accessed directly on computer will display Krona One with no problems, but the webpage hosted on GitHub will display generic font instead.

**Comment by codyqhogan** [comment]
Font is now fixed on all pages, the main issue was the font was not downloaded if the user did not have it, using Google fonts, this issue is resolved and the font is automatically used each time.
![dine86fixedfont](https://user-images.githubusercontent.com/108141435/178154224-3468950a-f2e9-45f2-bc2c-14541c905282.png)
